# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(307, 240)
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QPushButton(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(20, 0, 271, 51))
        self.result.setText("")
        self.result.setDefault(False)
        self.result.setFlat(False)
        self.result.setObjectName("result")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 289, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.display = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.display.setObjectName("display")
        self.verticalLayout.addWidget(self.display)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plus.setFocusPolicy(QtCore.Qt.TabFocus)
        self.plus.setAutoFillBackground(False)
        self.plus.setFlat(False)
        self.plus.setObjectName("plus")
        self.horizontalLayout.addWidget(self.plus)
        self.minus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.minus.setObjectName("minus")
        self.horizontalLayout.addWidget(self.minus)
        self.mult = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mult.setObjectName("mult")
        self.horizontalLayout.addWidget(self.mult)
        self.divis = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.divis.setObjectName("divis")
        self.horizontalLayout.addWidget(self.divis)
        self.enter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.enter.setObjectName("enter")
        self.horizontalLayout.addWidget(self.enter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 307, 22))
        self.menubar.setObjectName("menubar")
        Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculator)
        self.statusbar.setObjectName("statusbar")
        Calculator.setStatusBar(self.statusbar)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "MainWindow"))
        self.plus.setText(_translate("Calculator", "+"))
        self.minus.setText(_translate("Calculator", "-"))
        self.mult.setText(_translate("Calculator", "*"))
        self.divis.setText(_translate("Calculator", "/"))
        self.enter.setText(_translate("Calculator", "="))
